# Generated by Django 2.1.5 on 2019-02-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api_airports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airstrip_length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
